### ISSUE TITLE
Sink unable to work with Kafka 3.3.2

### ISSUE THREAD

**Issue by elnoxgdl** [Aiven-Open/opensearch-connector-for-apache-kafka#223]
Hi Team I'm getting this exception when trying to create a new connector.

I am using kafka 3.3.2 I'm placing all the jar files under the plugins path but no idea what could be causing this unless I missed some file?

```
Caused by: org.glassfish.jersey.server.ContainerException: java.lang.NoClassDefFoundError: Could not initialize class io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig
    at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
    at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
    at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:438)
    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:263)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
    ... 35 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig
    at io.aiven.kafka.connect.opensearch.OpensearchSinkConnector.config(OpensearchSinkConnector.java:77)
    at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:482)
    at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$2(AbstractHerder.java:372)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    ... 1 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.util.ServiceConfigurationError: io.aiven.kafka.connect.opensearch.spi.ConfigDefContributor: io.aiven.kafka.connect.opensearch.O
pensearchBasicAuthConfigurator Unable to get public no-arg constructor [in thread "pool-2-thread-1"]
    at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
    at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
    at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
    at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
    at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
    at io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig.addSpiConfigs(OpensearchSinkConnectorConfig.java:226)
    at io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig.baseConfigDef(OpensearchSinkConnectorConfig.java:212)
    at io.aiven.kafka.connect.opensearch.OpensearchSinkConnectorConfig.<clinit>(OpensearchSinkConnectorConfig.java:513)
    ... 8 more
```

**Comment by elnoxgdl** [comment]
Resolved:

For those wondering, you need to unzip and then copy the directory completly not the jars only. Thanks!
